version: '3.8'
services:

  db-mysql:
    image: mysql
    env_file:
      - .env
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      backend:
        ipv4_address: 172.20.0.10
      default:
    ports:
      - "127.0.0.1:3306:3306"

  web:
    image: 5app
    #build:
      #context: /home/ubik/app/shvirtd-example-python
      #dockerfile: dockerfile.python
    depends_on:
      - db-mysql
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PASSWOD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    networks:
      backend:
        ipv4_address: 172.20.0.5
      default:
    restart: always

  reverse-proxy:
    image: haproxy
    restart: always
    networks:
        backend: {}
    ports:
    - "127.0.0.1:8080:8080"
    volumes:
    - ./haproxy/reverse/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw

  ingress-proxy:
    image: nginx:latest
    restart: always
    network_mode: host
    volumes:
    - ./nginx/ingress/default.conf:/etc/nginx/conf.d/default.conf:rw
    - ./nginx/ingress/nginx.conf:/etc/nginx/nginx.conf:rw

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24
