FROM python:3.9-slim

WORKDIR /app

#RUN python3 -m venv venv

#RUN chmod +x main.py

COPY . /app

RUN pip install --trusted-host pypi.python.org -r /app/requirements.txt

EXPOSE 5000

WORKDIR /app

CMD ["python", "main.py"]

#HEALTHCECK -- interval=5s --timeout=3s CMD -f http://lockalhost:8080/healthz || exit 1
